import React from 'react';
import './AddItemModal.css';
import Icon from '../Icon';

const ProcurementDetailsModal = ({ request, onClose }) => {
  if (!request) return null;

  const getPriorityClass = (priority) => {
    switch (priority) {
      case 'HIGH': return 'high';
      case 'MEDIUM': return 'medium';
      case 'LOW': return 'low';
      default: return 'medium';
    }
  };

  const getStatusClass = (status) => {
    switch (status) {
      case 'PENDING': return 'pending';
      case 'APPROVED': return 'approved';
      case 'ORDERED': return 'ordered';
      case 'RECEIVED': return 'received';
      case 'CANCELLED': return 'cancelled';
      default: return 'pending';
    }
  };

  const formatDate = (date) => {
    if (!date) return 'N/A';
    try {
      const d = new Date(date);
      return d.toLocaleDateString('en-US', { 
        year: 'numeric', 
        month: 'long', 
        day: 'numeric',
        hour: '2-digit',
        minute: '2-digit'
      });
    } catch (e) {
      return 'N/A';
    }
  };

  return (
    <div className="modal-overlay" onClick={onClose}>
      <div className="modal-content add-item-modal" onClick={(e) => e.stopPropagation()}>
        <button className="modal-close" onClick={onClose}>
          <Icon name="x" size={24} />
        </button>
        <h2 className="modal-title">Procurement Request Details</h2>
        
        <div style={{ marginBottom: '20px' }}>
          <div style={{ 
            display: 'inline-block', 
            padding: '6px 12px', 
            borderRadius: '6px',
            fontSize: '12px',
            fontWeight: '500',
            backgroundColor: request.isAutoGenerated ? '#e3f2fd' : '#f3e5f5',
            color: request.isAutoGenerated ? '#1976d2' : '#7b1fa2'
          }}>
            {request.isAutoGenerated ? 'Auto-Generated' : 'Manual Request'}
          </div>
        </div>

        <div className="form-group">
          <label className="form-label">Request ID</label>
          <div style={{ 
            padding: '12px', 
            backgroundColor: '#f5f5f5', 
            borderRadius: '8px',
            fontFamily: 'monospace',
            fontSize: '14px'
          }}>
            {request.requestId || request.componentId || request._id || 'N/A'}
          </div>
        </div>

        <div className="form-row">
          <div className="form-group">
            <label className="form-label">Item Name</label>
            <div style={{ 
              padding: '12px', 
              backgroundColor: '#f5f5f5', 
              borderRadius: '8px',
              fontSize: '16px'
            }}>
              {request.itemName || request.name || 'N/A'}
            </div>
          </div>

          <div className="form-group">
            <label className="form-label">Quantity Needed</label>
            <div style={{ 
              padding: '12px', 
              backgroundColor: '#f5f5f5', 
              borderRadius: '8px',
              fontSize: '16px',
              fontWeight: '500'
            }}>
              {request.quantity || 0} units
            </div>
          </div>
        </div>

        <div className="form-row">
          <div className="form-group">
            <label className="form-label">Priority</label>
            <div style={{ marginTop: '8px' }}>
              <span className={`priority-badge ${getPriorityClass(request.priority)}`}>
                {request.priority || 'MEDIUM'}
              </span>
            </div>
          </div>

          <div className="form-group">
            <label className="form-label">Status</label>
            <div style={{ marginTop: '8px' }}>
              <span className={`status-badge ${getStatusClass(request.status)}`}>
                {request.status || 'PENDING'}
              </span>
            </div>
          </div>
        </div>

        {request.componentId && (
          <div className="form-group">
            <label className="form-label">Linked Component ID</label>
            <div style={{ 
              padding: '12px', 
              backgroundColor: '#f5f5f5', 
              borderRadius: '8px',
              fontFamily: 'monospace',
              fontSize: '14px'
            }}>
              {request.componentId}
            </div>
          </div>
        )}

        {request.category && (
          <div className="form-group">
            <label className="form-label">Category</label>
            <div style={{ 
              padding: '12px', 
              backgroundColor: '#f5f5f5', 
              borderRadius: '8px',
              fontSize: '16px'
            }}>
              {request.category}
            </div>
          </div>
        )}

        {request.description && (
          <div className="form-group">
            <label className="form-label">Description</label>
            <div style={{ 
              padding: '12px', 
              backgroundColor: '#f5f5f5', 
              borderRadius: '8px',
              fontSize: '14px',
              lineHeight: '1.5',
              whiteSpace: 'pre-wrap'
            }}>
              {request.description || 'No description provided'}
            </div>
          </div>
        )}

        {request.remarks && (
          <div className="form-group">
            <label className="form-label">Remarks</label>
            <div style={{ 
              padding: '12px', 
              backgroundColor: '#f5f5f5', 
              borderRadius: '8px',
              fontSize: '14px',
              lineHeight: '1.5',
              whiteSpace: 'pre-wrap'
            }}>
              {request.remarks || 'No remarks'}
            </div>
          </div>
        )}

        {request.requestedBy && (
          <div className="form-group">
            <label className="form-label">Requested By</label>
            <div style={{ 
              padding: '12px', 
              backgroundColor: '#f5f5f5', 
              borderRadius: '8px',
              fontSize: '16px'
            }}>
              {request.requestedBy}
            </div>
          </div>
        )}

        {request.createdAt && (
          <div className="form-group">
            <label className="form-label">Created At</label>
            <div style={{ 
              padding: '12px', 
              backgroundColor: '#f5f5f5', 
              borderRadius: '8px',
              fontSize: '14px'
            }}>
              {formatDate(request.createdAt)}
            </div>
          </div>
        )}

        <div className="modal-buttons">
          <button type="button" className="btn-cancel" onClick={onClose}>
            Close
          </button>
        </div>
      </div>
    </div>
  );
};

export default ProcurementDetailsModal;

